name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  push:
    branches:
      - main  # Executa quando há um push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - name: List files in dist directory
        run: ls -la dist

      - name: Commit and push the Snake Game
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Generate Snake Game from Contribution Grid"
          git push
